### PR TITLE
Dokku compat; see https://github.com/dokku/dokku-mongo

### PR DESCRIPTION
**Pull request by rvalyi**

### CODE REVIEW

**Comment by did** [comment]
thanks @rvalyi. Would you have time to write a guide about how to run Locomotive on Dokku? thanks!

**Comment by rvalyi** [comment]
@did 

Yes just point me the point in the doc.

But in short that is around 5-6 commands such . Like:

```
git push of instant-deploy to your Dokku install as an app called loco-app
dokku mongo:create loco
dokku mongo:link loco loco-app
dokku config:set "VAR_X=VALUE_X" with all your required s3 config.
```

then browse your locomotive app URL and you are done.

But if you tell me where I do it cleanly.

**Comment by did** [comment]
@rvalyi I definitively need you to write that down! I'm dealing with readme.io so that you can get an admin account in order to add this new guide. That'd be awesome!

**Comment by rvalyi** [comment]
@did you could also may be consider this for your doc:
http://gliderlabs.com/pagebuilder/latest/
a more complex example: http://gliderlabs.com/registrator/latest/

Really a simple glue command made by a genius programmer.

**Comment by rvalyi** [comment]
just to make it clear: the guy who created pagebuilder is Jeff Lindsay, the same guy who created dokku and a bunch of other genius open source projects...

**Pull request merged**
